package org.example.project.presentations.navigation

object AppRoute {
    const val Splash = "splash_screen"
    const val Login = "login_screen"
    const val Main = "main_screen"
    const val Profile = "profile"
    const val Notification = "notification_screen"
    const val Setting = "setting_screen"
    const val EditProfile = "edit_profile_screen"
    const val TranscriptTerm = "transcript_term_screen"
    const val TimetableScreen = "timetable_screen"
    const val Feedback = "feedback_screen"
    const val FeedbackDetail = "feedback_detail_screen"
    const val FeaturesScreen = "features_screen_screen"
    const val ExamSchedule = "exam_schedule_screen"
    const val GpaPredict = "gpa_predict_screen"
    const val DigitalStudentCard = "digital_student_card_screen"
    const val StudentClass = "student_class_screen"
    const val ClassSignUp = "class_sign_up_screen"
    const val ClassSignUpDetail = "class_sign_up_detail_screen"
    const val OfflineTimetableScreen = "offline_timetable_screen"
    const val TuitionPayment = "tuition_payment_screen"
    const val NewsScreen = "news_screen"
    const val Chat = "chat_screen"
    const val Application = "application_screen"
}